### ISSUE TITLE
FA-05-002: verifier has no minimum-header revision gate for opcodes, so QTruth executes under SEMCODE0

### ISSUE THREAD

**Issue by skulmakov-oss** [skulmakov-oss/Semantic#1732]
Umbrella: #1617
Module: 05 — `sm-format`
Audit HEAD: `4ac4d1a169902777e760e23eaee92aa233edc04d`
Severity: **P1**
Classification: **IDENTITY/TRUST-GAP · SEMANTIC-DRIFT · FALSE-READY**

## Trigger

`sm-format::Opcode` contains the post-baseline `QTruthAnd`, `QTruthOr`, `QTruthNot`, and `QTruthImpl` opcodes in reserved byte slots `0x17..0x1a`.

The `sm-ir` header selector promotes SemCode only for feature families such as f64/fx/text/sequence/closure/ownership/map/PRNG/application calls. It contains no QTruth-specific revision promotion, so a QTruth-only program can still be emitted with `MAGIC0` / `SEMCODE0`.

`sm-verify::decode_operands` accepts the QTruth opcodes structurally and does not attach a required capability or minimum SemCode revision to them. There is no general opcode→minimum-header-revision admission table.

## Claim / confidence source

`docs/spec/semcode.md` freezes existing header families and states that changing the meaning/admission interpretation of an existing header requires version review; silent mutation of an existing header family is forbidden.

The QTruth roadmap explicitly describes these as newly introduced opcodes added after the legacy lattice opcode family.

## Actual guarantee

Header identity currently gates only through cumulative capability bits. Any opcode whose verifier branch requires no new capability can be accepted under an older header even if that opcode was introduced after the header's baseline meaning.

For QTruth specifically:

```text
new QTruth opcode
→ emitter can choose SEMCODE0
→ header_spec_from_magic returns HEADER_V0
→ Opcode::from_byte recognizes QTruth
→ verifier finds no missing capability
→ VM may execute QTruth semantics
```

## Gap

The artifact version does not reliably identify the admitted opcode vocabulary. Old header families can silently acquire new executable semantics without a header/revision transition.

This is independent of FA-04-012's OWN0 component widening: that finding concerns ownership section vocabulary under SEMCOD11; this finding concerns instruction opcode vocabulary and missing minimum-revision admission metadata.

## Evidence

- `crates/sm-format/src/local_format.rs::Opcode`
- `crates/sm-ir/src/legacy_lowering.rs::emit_semcode` header selection
- `crates/sm-verify/src/lib.rs::decode_operands`
- `docs/roadmap/core_quad/inventory_qtruth_opcodes.md`
- `docs/roadmap/core_quad/qtruth_opcode_reservation.md`
- `docs/spec/semcode.md`

Phase A evidence only. **No repair during Phase A.**

**Comment by skulmakov-oss** [comment]
### Module 07 (`sm-verify`) cross-boundary evidence

Frozen audit SHA: `4ac4d1a169902777e760e23eaee92aa233edc04d`.

The verifier audit confirms this is not producer-only drift. `sm-verify` has an explicit unit test named `verifier_accepts_unsupported_qtruth_opcodes` which injects QTruth opcodes into a baseline artifact and asserts successful verification. `decode_operands()` admits QTruth opcodes without a minimum-header-revision check.

So the current negative/compatibility corpus actively records the widened old-header behavior as an expected verifier success. This strengthens the `QUALIFICATION-GAP / FALSE-READY` aspect of FA-05-002.

Phase A evidence only; no repair.

**Comment by skulmakov-oss** [comment]
**Repair Slice 2.1 complete — FA-05-002 fixed and merged.**

- **PR**: #1799, squash-merged as `50fbbe0560549e30b7f4b6f1394814c520201fb9`
- **Base**: `main` @ `f82cf7b101a0e68703af4237cd29e26138f28bee`

**Root cause**: `QTruthAnd`/`QTruthOr`/`QTruthNot`/`QTruthImpl` (`0x17`-`0x1A`) were introduced in #1455 with zero header or capability change across their entire rollout (#1455/#1457/#1459/#1461-1465/#1471). Header identity gates opcode admission only through cumulative capability bits; QTruth was the one opcode family in this slice's scope with no capability bit at all, so it could be silently admitted under `SEMCODE0` — a header revision that never claimed its semantics.

**Authoritative-minimum-revision decision**: no repository evidence (roadmap docs, spec, commit history) ever defined a minimum header revision for QTruth, so this was raised rather than guessed. Owner decision: mint `SEMCOD18` (epoch 0, rev 19) as QTruth's minimum, matching how every other opcode-introducing change in this repo's history got a dedicated header bump.

**Fix**: `Opcode::minimum_semcode_revision()` (new, `sm-format`) is the single, format-owned authority binding opcode vocabulary to header identity — **exhaustive over all 73 current `Opcode` variants, no wildcard** (compile-time proof: a temporary dummy variant without a matching arm produced `error[E0004]: non-exhaustive patterns`, demonstrated then reverted). `sm-verify` enforces `header.rev >= opcode.minimum_semcode_revision()` for every decoded instruction (new `VerificationCode::OpcodeRequiresNewerHeader`, deliberately distinct from `CapabilityViolation`), running **after** `decode_operands` so a structurally invalid instruction reports its real error rather than masking it behind a revision mismatch. `sm-ir`'s emitter promotes to `SEMCOD18` via `has_v18_qtruth_instr`, with a mechanical, fail-closed safety net (`emit_semcode_function` tracks the actual emitted opcode revision from real bytes and hard-fails on any drift from the chosen header) so a future opcode can't silently slip through.

**Scope discipline**: the same audit found other post-baseline, no-capability opcode families (`AddI32`/`TupleGet`/`MakeRecord`/`Assert`/etc.) with the same structural shape as QTruth's gap, but none has QTruth's roadmap-reservation evidence — filed as research-only follow-up **#1800**, no revisions assigned, no repair.

**Compatibility**: 0/21 git-tracked `.smc` artifacts affected; only 3 untracked local scratch artifacts (never part of the repo) newly rejected.

**Review loop**: 6 rounds, every finding fixed in-PR — emitter/authority disconnect, stale Foundation-profile range (extended per owner decision), the wildcard fallback, a fail-open revision-tracking guard, and a diagnostic-ordering bug where the revision gate could mask a real `OperandOutOfBounds`. Final HEAD reviewed clean by codex, CI fully green.

Executable opcode vocabulary is now mechanically bound to SemCode header identity; QTruth cannot be admitted under a header older than `SEMCOD18`, and any future opcode requiring a newer header must be given one explicitly or the build fails to compile.
